packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@itzcull/json-utils': ^0.0.3
catalogs:
  cli:
    '@antfu/ni': ^28.1.0
    '@itzcull/eslint-config': ^0.0.3
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.0
  testing:
    vitest: ^4.0.16
    vitest-package-exports: ^1.1.2
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.3
  utils:
    tinyexec: ^1.0.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
