packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@itzcull/json-utils': ^0.0.2
catalogs:
  cli:
    '@antfu/ni': ^25.0.0
    '@itzcull/eslint-config': ^0.0.3
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^7.0.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
